Reusable workflow for JAX-Pallas unit tests (#575)
The Jax, Pallas and Levanter unit-test workflows are almost identical,
the difference is the way they run the unit-tests and process the test
result data. To avoid code repeating and reduce the workflow count, it
is reasonable to have only one unit-test workflow that wraps changeable
part (test run script and test result processing) and outcomes the
results in a standard way.

---------

Co-authored-by: Yu-Hang 'Maxin' Tang <Tang.Maxin@gmail.com>

diff --git a/.github/workflows/_ci.yaml b/.github/workflows/_ci.yaml
--- a/.github/workflows/_ci.yaml
+++ b/.github/workflows/_ci.yaml
@@ -205,8 +205,21 @@ jobs:
     with:
       IMAGE: ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }}
       TEST_NAME: jax
-      ARTIFACT_NAME: artifact-jax-unit-test
-      BADGE_FILENAME: badge-jax-unit-test
+      EXECUTE: |
+        docker run --shm-size=1g --gpus all ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }} test-jax.sh -b backend-independent | tee test-backend-independent.log
+        docker run --shm-size=1g --gpus all ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }} test-jax.sh -b gpu | tee test-gpu.log
+      STATISTICS_SCRIPT: |
+        errors=$(cat test-*.log | grep -c 'ERROR:' || true)
+        failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true)
+        passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true)
+        total_tests=$((failed_tests + passed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-backend-independent.log
+        test-gpu.log
     secrets: inherit
 
   test-te:
@@ -240,8 +253,20 @@ jobs:
     with:
       IMAGE: ${{ needs.build-pallas.outputs.DOCKER_TAG_FINAL }}
       TEST_NAME: pallas
-      ARTIFACT_NAME: artifact-pallas-unit-test
-      BADGE_FILENAME: badge-pallas-unit-test
+      EXECUTE: |
+        docker run --shm-size=1g --gpus all --volume $PWD:/output ${{ needs.build-pallas.outputs.DOCKER_TAG_FINAL }} python /opt/jax/tests/pallas/pallas_test.py --xml_output_file /output/pallas_test.xml | tee test-pallas.log
+      STATISTICS_SCRIPT: |
+        curl -L -o yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$(dpkg --print-architecture) && chmod 777 yq;
+        total_tests=$(./yq '.testsuites."+@tests"' pallas_test.xml)
+        errors=$(./yq '.testsuites."+@errors"' pallas_test.xml)
+        failed_tests=$(./yq '.testsuites."+@failures"' pallas_test.xml)
+        passed_tests=$((total_tests - errors - failed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-pallas.log
     secrets: inherit
 
   test-levanter:
@@ -251,8 +276,22 @@ jobs:
     with:
       IMAGE: ${{ needs.build-levanter.outputs.DOCKER_TAG_FINAL }}
       TEST_NAME: levanter
-      ARTIFACT_NAME: artifact-levanter-unit-test
-      BADGE_FILENAME: badge-levanter-unit-test
+      EXECUTE: |
+        docker run --gpus all --shm-size=1g ${{ needs.build-levanter.outputs.DOCKER_TAG_FINAL }} \
+        bash -ec \
+        "pip install pytest && PYTHONPATH=/opt/levanter/tests:$PYTHONPATH pytest /opt/levanter/tests" | tee test-levanter.log
+      STATISTICS_SCRIPT: |
+        summary_line=$(tail -n1 test-levanter.log)
+        errors=$(echo $summary_line | grep -oE '[0-9]+ error' | awk '{print $1} END { if (!NR) print 0}')
+        failed_tests=$(echo $summary_line | grep -oE '[0-9]+ failed' | awk '{print $1} END { if (!NR) print 0}')
+        passed_tests=$(echo $summary_line | grep -oE '[0-9]+ passed' | awk '{print $1} END { if (!NR) print 0}')
+        total_tests=$((failed_tests + passed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-levanter.log
     secrets: inherit
 
   test-upstream-pax:
