Clean up exit code

diff --git a/.github/workflows/_ci.yaml b/.github/workflows/_ci.yaml
--- a/.github/workflows/_ci.yaml
+++ b/.github/workflows/_ci.yaml
@@ -542,7 +542,12 @@ jobs:
         echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
         echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
 
-        exit $failed_tests
+        echo "$failed_tests tests failed"
+        if [[ $failed_tests -gt 0 ]]; then
+            exit 1
+        else
+            exit 0
+        fi
 
       TIMEOUT_MINUTES: 120
       ARTIFACTS: |
diff --git a/.github/workflows/_transformer_engine_eks.yaml b/.github/workflows/_transformer_engine_eks.yaml
--- a/.github/workflows/_transformer_engine_eks.yaml
+++ b/.github/workflows/_transformer_engine_eks.yaml
@@ -99,7 +99,12 @@ jobs:
         echo "FAILED_TESTS=$failed_tests" >> $GITHUB_OUTPUT
         echo "TOTAL_TESTS=$total_tests" >> $GITHUB_OUTPUT
 
-        exit $failed_tests
+        echo "$failed_tests tests failed"
+        if [[ $failed_tests -gt 0 ]]; then
+            exit 1
+        else
+            exit 0
+        fi
 
     - name: Generate sitrep
       id: sitrep
