nsys-jax: don't assume recipe produces .sqlite
Previously there were some not-entirely-explicit dependencies between
different parts of post-processing that all used the SQLite export. With
2024.5 this broke, because nsys recipe nvtx_gpu_proj_trace does not produce
an .sqlite export as it used to.

The output data format has changed, and a patch is required to ensure
that it includes the TID with 2024.5..

Add a JAX-based communication test and use it to add end-to-end testing
of nsys-jax in the pipeline. Add a new communication analysis recipe to
allow prompt summarisation of communication data in profiles.

Scale diagram heights better when there are many modules.

diff --git a/.github/workflows/_ci.yaml b/.github/workflows/_ci.yaml
--- a/.github/workflows/_ci.yaml
+++ b/.github/workflows/_ci.yaml
@@ -299,6 +299,84 @@ jobs:
         test-gpu.log
     secrets: inherit
 
+  test-nsys-jax:
+    needs: build-jax
+    if: inputs.ARCHITECTURE == 'amd64' # arm64 runners n/a
+    uses: ./.github/workflows/_test_unit.yaml
+    with:
+      TEST_NAME: nsys-jax
+      EXECUTE: |
+        set -o pipefail
+        num_tests=0
+        num_failures=0
+        GPUS_PER_NODE=$(nvidia-smi -L | grep -c '^GPU')
+        for mode in 1-process 2-process process-per-gpu; do
+          DOCKER="docker run --shm-size=1g --gpus all --env XLA_FLAGS=--xla_gpu_enable_command_buffer= --env XLA_PYTHON_CLIENT_MEM_FRACTION=0.9 -v ${PWD}:/opt/output ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }}"
+          if [[ "${mode}" == "1-process" ]]; then
+            PROCESS_COUNT=1
+            ARGS=""
+          elif [[ "${mode}" == "2-process" ]]; then
+            # Use two processes with GPUS_PER_NODE/2 GPUs per process in the hope that
+            # this will flush out more bugs than process-per-node or process-per-GPU.
+            PROCESS_COUNT=2
+            ARGS="--process-id RANK --process-count ${PROCESS_COUNT} --coordinator-address 127.0.0.1:12345 --gpus-per-process $((GPUS_PER_NODE/2)) --distributed"
+          else
+            PROCESS_COUNT=${GPUS_PER_NODE}
+            ARGS="--process-id RANK --process-count ${PROCESS_COUNT} --coordinator-address 127.0.0.1:12345 --gpus-per-process 1 --distributed"
+          fi
+          for collection in full partial; do
+            NSYS_JAX="nsys-jax"
+            if [[ "${mode}" == "1-process" ]]; then
+              # We will not run nsys-jax-combine, so run analyses eagerly
+              NSYS_JAX+=" --nsys-jax-analysis communication --nsys-jax-analysis summary"
+            fi
+            NSYS_JAX+=" --output=/opt/output/${mode}-${collection}-execution-%q{RANK}"
+            if [[ "${collection}" == "partial" ]]; then
+              NSYS_JAX+=" --capture-range=cudaProfilerApi --capture-range-end=stop"
+              # nvbug/4801401
+              NSYS_JAX+=" --sample=none"
+            fi
+            set +e
+            ${DOCKER} jax-nccl-test-multiprocess.sh RANK ${PROCESS_COUNT} ${NSYS_JAX} \
+              -- jax-nccl-test.py ${ARGS} |& tee ${mode}-${collection}-execution.log
+            num_failures=$((num_failures + ($? != 0)))
+            set -e
+            num_tests=$((num_tests + 1))
+          done
+          if [[ "${mode}" != "1-process" ]]; then
+            # Run nsys-jax-combine
+            NSYS_JAX_COMBINE="nsys-jax-combine --analysis communication --analysis summary --output=/opt/output/${mode}-${collection}-execution.zip"
+            for (( i=0; i<PROCESS_COUNT; i++ )); do
+              NSYS_JAX_COMBINE+=" /opt/output/${mode}-${collection}-execution-${i}.zip"
+            done
+            set +e
+            ${DOCKER} ${NSYS_JAX_COMBINE} |& tee ${mode}-${collection}-execution-combine.log
+            num_failures=$((num_failures + ($? != 0)))
+            set -e
+            num_tests=$((num_tests + 1))
+          fi
+        done
+        ls -R .
+        echo "NSYS_JAX_TEST_COUNT=${num_tests}" >> $GITHUB_ENV
+        echo "NSYS_JAX_FAIL_COUNT=${num_failures}" >> $GITHUB_ENV
+        exit $num_failures
+      STATISTICS_SCRIPT: |
+        num_passed=$(( NSYS_JAX_TEST_COUNT - NSYS_JAX_FAIL_COUNT ))
+        num_errors=0
+        echo "TOTAL_TESTS=${NSYS_JAX_TEST_COUNT}" >> $GITHUB_OUTPUT
+        echo "ERRORS=0" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${num_passed}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${NSYS_JAX_FAIL_COUNT}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        # nsys-jax logfiles
+        *process-*-execution.log
+        # nsys-jax output for the case that doesn't use nsys-jax-combine
+        1-process-*-execution-0.zip
+        # nsys-jax-combine output/logfiles
+        *process*-*-execution.zip
+        *-execution-combine.log
+    secrets: inherit
+
   # test-equinox:
   #   needs: build-equinox
   #   if: inputs.ARCHITECTURE == 'amd64' # arm64 runners n/a
