fix test and create output

diff --git a/.github/workflows/_ci.yaml b/.github/workflows/_ci.yaml
--- a/.github/workflows/_ci.yaml
+++ b/.github/workflows/_ci.yaml
@@ -706,7 +706,15 @@ jobs:
           test-axlearn.sh --directory "." --output "/opt/output/" --test-files "/opt/axlearn/axlearn/common/*_test.py" 
         EOF
       STATISTICS_SCRIPT: |
-        echo "Todo"
+        # Parse the summary.txt file to count passed/failed/error tests
+        # Adjust greps if your output format changes.
+        passed_tests=$(grep -c ": PASSED" /opt/output/summary.txt || true)
+        failed_tests=$(grep -c ": FAILED" /opt/output/summary.txt || true)
+        total_tests=$((failed_tests + passed_tests))
+
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
       ARTIFACTS: |
         test-backend-independent.log
     secrets: inherit
