Fix levanter test run

diff --git a/.github/workflows/_ci.yaml b/.github/workflows/_ci.yaml
--- a/.github/workflows/_ci.yaml
+++ b/.github/workflows/_ci.yaml
@@ -206,17 +206,17 @@ jobs:
       IMAGE: ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }}
       TEST_NAME: jax
       EXECUTE: |
-        docker run --shm-size=1g --gpus all ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }} test-jax.sh -b backend-independent | tee test-backend-independent.log;
+        docker run --shm-size=1g --gpus all ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }} test-jax.sh -b backend-independent | tee test-backend-independent.log
         docker run --shm-size=1g --gpus all ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }} test-jax.sh -b gpu | tee test-gpu.log
       STATISTICS_SCRIPT: |
-        errors=$(cat test-*.log | grep -c 'ERROR:' || true);
-        failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true);
-        passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true);
-        total_tests=$((failed_tests + passed_tests));
-        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT;
-        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT;
-        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT;
-        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT;
+        errors=$(cat test-*.log | grep -c 'ERROR:' || true)
+        failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true)
+        passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true)
+        total_tests=$((failed_tests + passed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
       ARTIFACTS: |
         test-backend-independent.log
         test-gpu.log
@@ -263,10 +263,10 @@ jobs:
         errors=$(./yq '.testsuites."+@errors"' pallas_test.xml)
         failed_tests=$(./yq '.testsuites."+@failures"' pallas_test.xml)
         passed_tests=$((total_tests - errors - failed_tests))
-        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT;
-        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT;
-        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT;
-        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT;
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
       ARTIFACTS: |
         test-pallas.log
       ARTIFACT_NAME: artifact-pallas-unit-test
@@ -281,17 +281,17 @@ jobs:
       IMAGE: ${{ needs.build-levanter.outputs.DOCKER_TAG_FINAL }}
       TEST_NAME: levanter
       EXECUTE: |
-        docker run --gpus all --shm-size=1g ${{ needs.build-levanter.outputs.DOCKER_TAG_FINAL }} bash -ec "pip install flake8 pytest test-util && pytest /opt/levanter/tests" | tee test-levanter.log
+        docker run --gpus all --shm-size=1g ${{ needs.build-levanter.outputs.DOCKER_TAG_FINAL }} bash -ec "pip install pytest && pytest /opt/levanter/tests" | tee test-levanter.log
       STATISTICS_SCRIPT: |
-        summary_line=$(tail test-levanter.log);
-        errors=$(echo $summary_line | grep -oE '[0-9]+ error' | awk '{print $1} END { if (!NR) print 0}');
-        failed_tests=$(echo $summary_line | grep -oE '[0-9]+ failed' | awk '{print $1} END { if (!NR) print 0}');
-        passed_tests=$(echo $summary_line | grep -oE '[0-9]+ passed' | awk '{print $1} END { if (!NR) print 0}');
-        total_tests=$((failed_tests + passed_tests));
-        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT;
-        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT;
-        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT;
-        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT;
+        summary_line=$(tail test-levanter.log)
+        errors=$(echo $summary_line | grep -oE '[0-9]+ error' | awk '{print $1} END { if (!NR) print 0}')
+        failed_tests=$(echo $summary_line | grep -oE '[0-9]+ failed' | awk '{print $1} END { if (!NR) print 0}')
+        passed_tests=$(echo $summary_line | grep -oE '[0-9]+ passed' | awk '{print $1} END { if (!NR) print 0}')
+        total_tests=$((failed_tests + passed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
       ARTIFACTS: |
         test-levanter.log
       ARTIFACT_NAME: artifact-levanter-unit-test
