[skip ci] Sandbox run

diff --git a/.github/workflows/_ci.yaml b/.github/workflows/_ci.yaml
--- a/.github/workflows/_ci.yaml
+++ b/.github/workflows/_ci.yaml
@@ -205,6 +205,21 @@ jobs:
     with:
       IMAGE: ${{ needs.build-jax.outputs.DOCKER_TAG_FINAL }}
       TEST_NAME: jax
+      EXECUTE: |
+        docker run --gpus all ${{ inputs.JAX_IMAGE }} test-jax.sh -b backend-independent | tee test-backend-independent.log;
+        docker run --gpus all ${{ inputs.JAX_IMAGE }} test-jax.sh -b gpu | tee test-gpu.log
+      STATISTICS_SCRIPT: |
+        errors=$(cat test-*.log | grep -c 'ERROR:' || true);
+        failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true);
+        passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true);
+        total_tests=$((failed_tests + passed_tests));
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT;
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT;
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT;
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT;
+      ARTIFACTS: |
+        test-backend-independent.log
+        test-gpu.log
       ARTIFACT_NAME: artifact-jax-unit-test
       BADGE_FILENAME: badge-jax-unit-test
     secrets: inherit
@@ -240,8 +255,24 @@ jobs:
     with:
       IMAGE: ${{ needs.build-pallas.outputs.DOCKER_TAG_FINAL }}
       TEST_NAME: pallas
+      EXECUTE: |
+        docker run --gpus all ${{ inputs.JAX_IMAGE }} test-jax.sh -b backend-independent | tee test-backend-independent.log;
+        docker run --gpus all ${{ inputs.JAX_IMAGE }} test-jax.sh -b gpu | tee test-gpu.log
+      STATISTICS_SCRIPT: |
+        curl -L -o yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$(dpkg --print-architecture) && chmod 777 yq;
+        total_tests=$(./yq '.testsuites."+@tests"' pallas_test.xml)
+        errors=$(./yq '.testsuites."+@errors"' pallas_test.xml)
+        failed_tests=$(./yq '.testsuites."+@failures"' pallas_test.xml)
+        passed_tests=$((total_tests - errors - failed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT;
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT;
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT;
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT;
+      ARTIFACTS: |
+        test-pallas.log
       ARTIFACT_NAME: artifact-pallas-unit-test
       BADGE_FILENAME: badge-pallas-unit-test
+
     secrets: inherit
 
   test-upstream-pax:
