REMOVE: disable fail test and test success path

diff --git a/.github/workflows/_ci_tmp.yaml b/.github/workflows/_ci_tmp.yaml
--- a/.github/workflows/_ci_tmp.yaml
+++ b/.github/workflows/_ci_tmp.yaml
@@ -55,8 +55,8 @@ jobs:
           ls -lah patches
           echo "Changes in manifest file and patch folder"
           git diff
-  fail:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Pass
-        run: exit 1
+  #fail:
+  #  runs-on: ubuntu-22.04
+  #  steps:
+  #    - name: Pass
+  #      run: exit 1
