refactor

diff --git a/.github/workflows/_sandbox.yaml b/.github/workflows/_sandbox.yaml
--- a/.github/workflows/_sandbox.yaml
+++ b/.github/workflows/_sandbox.yaml
@@ -1,41 +1,112 @@
 name: "~Sandbox"
 
 on:
-  workflow_dispatch:
+  push:
 
 jobs:
-  sandbox:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Print usage
-        run: |
-          cat << EOF
-          This is an empty workflow file located in the main branch of your
-          repository. It serves as a testing ground for new GitHub Actions on
-          development branches before merging them to the main branch. By
-          defining and overloading this workflow on your development branch,
-          you can test new actions without affecting your main branch, ensuring
-          a smooth integration process once the changes are ready to be merged.
+  test-jax:
+    uses: ./.github/workflows/_test_unit.yaml
+    with:
+      TEST_NAME: jax
+      EXECUTE: |
+        docker run --shm-size=1g --gpus all ghcr.io/nvidia/jax:jax test-jax.sh -b backend-independent |& tee test-backend-independent.log
+        docker run --shm-size=1g --gpus all ghcr.io/nvidia/jax:jax test-jax.sh -b gpu |& tee test-gpu.log
+      STATISTICS_SCRIPT: |
+        errors=$(cat test-*.log | grep -c 'ERROR:' || true)
+        failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true)
+        passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true)
+        total_tests=$((failed_tests + passed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-backend-independent.log
+        test-gpu.log
+    secrets: inherit
 
-          Usage:
-          
-          1. In your development branch, modify the sandbox.yml workflow file
-             to include the new actions you want to test. Make sure to commit
-             the changes to the development branch.
-          2. Navigate to the 'Actions' tab in your repository, select the
-             '~Sandbox' workflow, and choose your development branch from the
-             branch dropdown menu. Click on 'Run workflow' to trigger the
-             workflow on your development branch.
-          3. Once you have tested and verified the new actions in the Sandbox
-             workflow, you can incorporate them into your main workflow(s) and
-             merge the development branch into the main branch. Remember to
-             revert the changes to the sandbox.yml file in the main branch to
-             keep it empty for future testing.
-          EOF
+  test-pallas:
+    uses: ./.github/workflows/_test_unit.yaml
+    with:
+      TEST_NAME: pallas
+      EXECUTE: |
+        docker run --shm-size=1g --gpus all --volume $PWD:/output ghcr.io/nvidia/jax:jax python /opt/jax/tests/pallas/pallas_test.py --xml_output_file /output/pallas_test.xml |& tee test-pallas.log
+      STATISTICS_SCRIPT: |
+        curl -L -o yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$(dpkg --print-architecture) && chmod 777 yq;
+        total_tests=$(./yq '.testsuites."+@tests"' pallas_test.xml)
+        errors=$(./yq '.testsuites."+@errors"' pallas_test.xml)
+        failed_tests=$(./yq '.testsuites."+@failures"' pallas_test.xml)
+        passed_tests=$((total_tests - errors - failed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-pallas.log
+    secrets: inherit
+
+  test-triton:
+    uses: ./.github/workflows/_test_unit.yaml
+    with:
+      TEST_NAME: triton
+      EXECUTE: |
+        docker run --shm-size=1g --gpus all --volume $PWD:/output ghcr.io/nvidia/jax:triton python /opt/jax-triton/tests/triton_call_test.py --xml_output_file /output/triton_test.xml |& tee test-triton.log
+      STATISTICS_SCRIPT: |
+        curl -L -o yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$(dpkg --print-architecture) && chmod 777 yq;
+        total_tests=$(./yq '.testsuites."+@tests"' triton_test.xml)
+        errors=$(./yq '.testsuites."+@errors"' triton_test.xml)
+        failed_tests=$(./yq '.testsuites."+@failures"' triton_test.xml)
+        passed_tests=$((total_tests - errors - failed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-triton.log
+    secrets: inherit
+
+  test-levanter:
+    uses: ./.github/workflows/_test_unit.yaml
+    with:
+      TEST_NAME: levanter
+      EXECUTE: |
+        docker run --gpus all --shm-size=1g ghcr.io/nvidia/jax:levanter \
+        bash -ec \
+        "pip install pytest && PYTHONPATH=/opt/levanter/tests:$PYTHONPATH pytest /opt/levanter/tests" |& tee test-levanter.log
+      STATISTICS_SCRIPT: |
+        summary_line=$(tail -n1 test-levanter.log)
+        errors=$(echo $summary_line | grep -oE '[0-9]+ error' | awk '{print $1} END { if (!NR) print 0}')
+        failed_tests=$(echo $summary_line | grep -oE '[0-9]+ failed' | awk '{print $1} END { if (!NR) print 0}')
+        passed_tests=$(echo $summary_line | grep -oE '[0-9]+ passed' | awk '{print $1} END { if (!NR) print 0}')
+        total_tests=$((failed_tests + passed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-levanter.log
+    secrets: inherit
+
+  test-te:
+    uses: ./.github/workflows/_test_unit.yaml
+    with:
+      TEST_NAME: te
+      EXECUTE: |
+        docker run --gpus all --shm-size=1g ghcr.io/nvidia/jax:upstream-pax -v $PWD:/log \
+        bash -ec \
+        "pip install pytest-reportlog && pytest --report-log=log/pytest-report.jsonl ${SRC_PATH_TE}/tests/jax" |& tee test-te.log
+      STATISTICS_SCRIPT: |
+        summary_line=$(tail -n1 test-te.log)
+        errors=$(echo $summary_line | grep -oE '[0-9]+ error' | awk '{print $1} END { if (!NR) print 0}')
+        passed_tests=$(cat pytest-report.jsonl | jq -r 'select(."$report_type" == "CollectReport" and .outcome == "passed") | .outcome' | wc -l)
+        failed_tests=$(cat pytest-report.jsonl | jq -r 'select(."$report_type" == "CollectReport" and .outcome == "failed") | .outcome' | wc -l)          
+        total_tests=$((failed_tests + passed_tests))
+        echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        test-te.log
+        pytest-report.jsonl
+    secrets: inherit
diff --git a/.github/workflows/_test_unit.yaml b/.github/workflows/_test_unit.yaml
--- a/.github/workflows/_test_unit.yaml
+++ b/.github/workflows/_test_unit.yaml
@@ -13,7 +13,7 @@ on:
         required: true
       EXECUTE:
         type: string
-        description: 'Test command to run'
+        description: 'Test command to run in the container'
         required: false
       STATISTICS_SCRIPT:
         type: string
@@ -68,14 +68,8 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Pull test image
-        shell: bash -x -e {0}
-        run: |
-          docker pull ${{ inputs.IMAGE }}
-
       - name: Run tests
         shell: bash -x -e {0}
-        # todo: distinguish between test failures and errors
         continue-on-error: true
         run: |
           ${{ inputs.EXECUTE }}
@@ -87,34 +81,47 @@ jobs:
         run: |
           ${{ inputs.STATISTICS_SCRIPT }}
 
-      - name: Generate sitrep
+      - name: Summarize test statistics
+        id: summary
         shell: bash -x -e {0}
-        continue-on-error: ${{ github.event_name == 'schedule' }}
         run: |
           # bring in utility functions
           source .github/workflows/scripts/to_json.sh
-
-          badge_label='${{ inputs.TEST_NAME }} ${{ matrix.GPU_ARCH }} Unit'
 
           total_tests=${{ steps.test-stats.outputs.TOTAL_TESTS }}
           errors=${{ steps.test-stats.outputs.ERRORS }}
           failed_tests=${{ steps.test-stats.outputs.FAILED_TESTS }}
           passed_tests=${{ steps.test-stats.outputs.PASSED_TESTS }}
-          
+
           if [[ ${errors} > 0 ]] || [[ ${total_tests} == 0 ]]; then
-            badge_message='error'
-            badge_color=red
-            summary='${{ inputs.TEST_NAME }} unit test on ${{ matrix.GPU_ARCH }} did not complete due to errors.'
+            echo "badge_color='red'" >> $GITHUB_OUTPUT
+            echo "badge_message='error'" >> $GITHUB_OUTPUT
+            echo "summary='${{ inputs.TEST_NAME }} unit test on ${{ matrix.GPU_ARCH }} did not complete due to errors.'" >> $GITHUB_OUTPUT
+            exit 1
           else
-            badge_message="${passed_tests}/${total_tests} passed"
             if [[ ${failed_tests} == 0 ]]; then
-              badge_color=brightgreen
+              echo "badge_color='brightgreen'" >> $GITHUB_OUTPUT
             else
-              badge_color=yellow
+              echo "badge_color='yellow'" >> $GITHUB_OUTPUT
             fi
-            summary="${{ inputs.TEST_NAME }} unit test on ${{ matrix.GPU_ARCH }}: $badge_message"
+            echo "badge_message='${passed_tests}/${total_tests} passed'" >> $GITHUB_OUTPUT
+            echo "summary='${{ inputs.TEST_NAME }} unit test on ${{ matrix.GPU_ARCH }}: ${total_tests} total tests, ${error} errors, ${passed_tests} passed, ${failed_tests} failed.'" >> $GITHUB_OUTPUT
           fi
 
+      - name: Generate sitrep
+        id: sitrep
+        if: "!cancelled()"
+        shell: bash -x -e {0}
+        run: |
+          badge_label='${{ inputs.TEST_NAME }} ${{ matrix.GPU_ARCH }} Unit'
+
+          total_tests=${{ steps.test-stats.outputs.TOTAL_TESTS }} \
+          errors=${{ steps.test-stats.outputs.ERRORS }} \
+          failed_tests=${{ steps.test-stats.outputs.FAILED_TESTS }} \
+          passed_tests=${{ steps.test-stats.outputs.PASSED_TESTS }} \
+          summary="${{ steps.summary.outputs.summary }}" \
+          badge_message="${{ steps.summary.outputs.badge_message }}" \
+          badge_color="${{ steps.summary.outputs.badge_color }}" \
           to_json \
             summary \
             errors total_tests passed_tests failed_tests \
@@ -123,12 +130,13 @@ jobs:
 
           schemaVersion=1 \
           label="${badge_label}" \
-          message="${badge_message}" \
-          color="${badge_color}" \
+          message="${{ steps.summary.outputs.badge_message }}" \
+          color="${{ steps.summary.outputs.badge_color }}" \
           to_json schemaVersion label message color \
           > ${{ env.BADGE_FILENAME_FULL }}
 
       - name: Upload artifacts
+        if: "!cancelled()"
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.ARTIFACT_NAME_FULL }}
