update sandbox with github issue update and fail-fast=false everywhere

diff --git a/.github/workflows/_sandbox.yaml b/.github/workflows/_sandbox.yaml
--- a/.github/workflows/_sandbox.yaml
+++ b/.github/workflows/_sandbox.yaml
@@ -21,6 +21,10 @@ on:
 
 env:
   UPLD_IMAGE: ghcr.io/nvidia/jax-toolbox-internal
+  PAX_ASSIGNEE: ashors1
+  T5X_ASSIGNEE: terrykong
+  JAX_ASSIGNEE: yhtang
+  STAKEHOLDERS: "@ashors1 @terrykong @yhtang"
 
 permissions:
   contents: read  # to fetch code
@@ -206,6 +210,7 @@ jobs:
   test-t5x-ff:
     needs: [metadata, build-t5x-ff]
     strategy:
+      fail-fast: false
       max-parallel: 1
       matrix:
         base_tag: ${{fromJson(needs.metadata.outputs.TAGS_BETWEEN)}}
@@ -218,16 +223,21 @@ jobs:
     if: (success() || failure()) && needs.metadata.outputs.FRAMEWORK_BASE == 't5x'
     needs: [metadata, test-t5x-ff]
     runs-on: ubuntu-22.04
+    permissions:
+      issues: write
     steps:
       - name: Create table summarizing
+        id: summary-table
         run: |
+          set -ou pipefail
           json_data=$(curl -s -H "Authorization: Bearer ${{ github.token }}" "https://api.github.com/repos/NVIDIA/JAX-Toolbox/actions/runs/${{ github.run_id }}/jobs")
           name_conclusion_array=()
           while IFS= read -r line; do
             name_conclusion_array+=("$line")
           done < <(echo "$json_data" | jq -r '.jobs[] | select(.name | startswith("test-t5x-ff") and contains("outcome")) | "\(.name)\t\(.conclusion)"')
         
-          cat <<EOF | tee -a $GITHUB_STEP_SUMMARY
+          TABLE_MD=$(
+          cat <<EOF
           | Rewind to | Test result | Image |
           | --- | --- | --- |
           EOF
@@ -238,7 +248,7 @@ jobs:
             job_step_name=$(echo "${name_conclusion_array[$i]}" | cut -f1)
             conclusion=$(echo "${name_conclusion_array[$i]}" | cut -f2)
             if [[ ! "$job_step_name" == *$tag* ]]; then
-              echo "The runs from the GH API ($name_conclusion_array) do not align with TAGS_BETWEEN=${{ needs.metadata.outputs.TAGS_BETWEEN }}"
+              echo "The runs from the GH API ($name_conclusion_array) do not align with TAGS_BETWEEN=${{ needs.metadata.outputs.TAGS_BETWEEN }}" >&2
               exit 1
             fi
             echo "| $tag | $conclusion | ${{ needs.metadata.outputs.UPLD_IMAGE }}:${{ github.run_id }}-$tag-ff-t5x-to-${{ needs.metadata.outputs.BROKEN_DATE }} |"
@@ -246,14 +256,46 @@ jobs:
             if [[ $conclusion == success ]]; then
               last_success_img_date=$tag
             fi
-          done | tee -a $GITHUB_STEP_SUMMARY
-          echo -e "| | failure <br> (assumed broken) | ${{ inputs.BROKEN_IMAGE }} (BROKEN_IMAGE) |\n" | tee -a $GITHUB_STEP_SUMMARY
+          done
+          echo -e "| | failure <br> (assumed broken) | ${{ inputs.BROKEN_IMAGE }} (BROKEN_IMAGE) |\n"
 
           if [[ -z "$last_success_img_date" ]]; then
             echo "Found a working base nightly image (based on $last_success_img_date)); issue likely lies in more recent base nightly images."
+            echo "ASSIGNEE=${{ env.JAX_ASSIGNEE }}" >> $GITHUB_OUTPUT
           else
             echo "Cannot find a working base nightly image; issue likely lies in the ${{ needs.metadata.outputs.FRAMEWORK_BASE }} libraries."
-          fi | tee -a $GITHUB_STEP_SUMMARY
+            echo "ASSIGNEE=${{ env.T5X_ASSIGNEE }}" >> $GITHUB_OUTPUT
+          fi
+          )
+          ret_code=$?
+
+          # Writes to both the step summary and the github output
+          echo 'TABLE_MD<<EOF' >> $GITHUB_OUTPUT
+          echo "$TABLE_MD" | tee -a $GITHUB_STEP_SUMMARY >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+
+          exit $ret_code
+
+      - uses: octokit/request-action@v2.x
+        with:
+          #route: POST /repos/{owner_and_repo}/issues
+          route: PATCH /repos/{owner_and_repo}/issues/{issue_number}
+          owner_and_repo: ${{ github.repository }}
+          issue_number: 218 # DELETE ME
+          title: |
+            |
+            [Bot] ${{ needs.metadata.outputs.FRAMEWORK_BASE }} test failures on ${{ needs.metadata.outputs.BROKEN_DATE }}
+          body: |
+            | 
+            * Github Action run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} |
+  
+            ${{ steps.summary-table.outputs.TABLE_MD }}
+            
+            ${{ env.STAKEHOLDERS }}
+          assignee: ${{ steps.summary-table.outputs.ASSIGNEE }}
+          labels: "[\"auto-triage\"]"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
   ########
   ## PAX #
@@ -316,6 +358,7 @@ jobs:
   test-pax-ff:
     needs: [metadata, build-pax-ff]
     strategy:
+      fail-fast: false
       max-parallel: 1
       matrix:
         base_tag: ${{fromJson(needs.metadata.outputs.TAGS_BETWEEN)}}
@@ -328,16 +371,21 @@ jobs:
     if: (success() || failure()) && needs.metadata.outputs.FRAMEWORK_BASE == 'pax'
     needs: [metadata, test-pax-ff]
     runs-on: ubuntu-22.04
+    permissions:
+      issues: write
     steps:
       - name: Create table summarizing
+        id: summary-table
         run: |
+          set -ou pipefail
           json_data=$(curl -s -H "Authorization: Bearer ${{ github.token }}" "https://api.github.com/repos/NVIDIA/JAX-Toolbox/actions/runs/${{ github.run_id }}/jobs")
           name_conclusion_array=()
           while IFS= read -r line; do
             name_conclusion_array+=("$line")
           done < <(echo "$json_data" | jq -r '.jobs[] | select(.name | startswith("test-pax-ff") and contains("outcome")) | "\(.name)\t\(.conclusion)"')
         
-          cat <<EOF | tee -a $GITHUB_STEP_SUMMARY
+          TABLE_MD=$(
+          cat <<EOF
           | Rewind to | Test result | Image |
           | --- | --- | --- |
           EOF
@@ -348,7 +396,7 @@ jobs:
             job_step_name=$(echo "${name_conclusion_array[$i]}" | cut -f1)
             conclusion=$(echo "${name_conclusion_array[$i]}" | cut -f2)
             if [[ ! "$job_step_name" == *$tag* ]]; then
-              echo "The runs from the GH API ($name_conclusion_array) do not align with TAGS_BETWEEN=${{ needs.metadata.outputs.TAGS_BETWEEN }}"
+              echo "The runs from the GH API ($name_conclusion_array) do not align with TAGS_BETWEEN=${{ needs.metadata.outputs.TAGS_BETWEEN }}" >&2
               exit 1
             fi
             echo "| $tag | $conclusion | ${{ needs.metadata.outputs.UPLD_IMAGE }}:${{ github.run_id }}-$tag-ff-pax-to-${{ needs.metadata.outputs.BROKEN_DATE }} |"
@@ -356,11 +404,43 @@ jobs:
             if [[ $conclusion == success ]]; then
               last_success_img_date=$tag
             fi
-          done | tee -a $GITHUB_STEP_SUMMARY
-          echo -e "| | failure <br> (assumed broken) | ${{ inputs.BROKEN_IMAGE }} (BROKEN_IMAGE) |\n" | tee -a $GITHUB_STEP_SUMMARY
+          done
+          echo -e "| | failure <br> (assumed broken) | ${{ inputs.BROKEN_IMAGE }} (BROKEN_IMAGE) |\n"
 
           if [[ -z "$last_success_img_date" ]]; then
             echo "Found a working base nightly image (based on $last_success_img_date)); issue likely lies in more recent base nightly images."
+            echo "ASSIGNEE=${{ env.JAX_ASSIGNEE }}" >> $GITHUB_OUTPUT
           else
             echo "Cannot find a working base nightly image; issue likely lies in the ${{ needs.metadata.outputs.FRAMEWORK_BASE }} libraries."
-          fi | tee -a $GITHUB_STEP_SUMMARY
+            echo "ASSIGNEE=${{ env.PAX_ASSIGNEE }}" >> $GITHUB_OUTPUT
+          fi
+          )
+          ret_code=$?
+
+          # Writes to both the step summary and the github output
+          echo 'TABLE_MD<<EOF' >> $GITHUB_OUTPUT
+          echo "$TABLE_MD" | tee -a $GITHUB_STEP_SUMMARY >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+
+          exit $ret_code
+      
+      - uses: octokit/request-action@v2.x
+        with:
+          #route: POST /repos/{owner_and_repo}/issues
+          route: PATCH /repos/{owner_and_repo}/issues/{issue_number}
+          owner_and_repo: ${{ github.repository }}
+          issue_number: 215 # DELETE ME
+          title: |
+            |
+            [Bot] ${{ needs.metadata.outputs.FRAMEWORK_BASE }} test failures on ${{ needs.metadata.outputs.BROKEN_DATE }}
+          body: |
+            | 
+            * Github Action run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} |
+  
+            ${{ steps.summary-table.outputs.TABLE_MD }}
+            
+            ${{ env.STAKEHOLDERS }}
+          assignee: ${{ steps.summary-table.outputs.ASSIGNEE }}
+          labels: "[\"auto-triage\"]"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
