try without failure

diff --git a/.github/workflows/_sandbox.yaml b/.github/workflows/_sandbox.yaml
--- a/.github/workflows/_sandbox.yaml
+++ b/.github/workflows/_sandbox.yaml
@@ -40,7 +40,7 @@ jobs:
              keep it empty for future testing.
           EOF
 
-      - name: Mimic build failure
-        run: |
-          echo "Pretend Docker build fails here"
-          exit 1
+      # - name: Mimic build failure
+      #   run: |
+      #     echo "Pretend Docker build fails here"
+      #     exit 1
