test single-GPU CI execution of nsys-jax

diff --git a/.github/workflows/_sandbox.yaml b/.github/workflows/_sandbox.yaml
--- a/.github/workflows/_sandbox.yaml
+++ b/.github/workflows/_sandbox.yaml
@@ -5,37 +5,46 @@ on:
 
 jobs:
   sandbox:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Print usage
-        run: |
-          cat << EOF
-          This is an empty workflow file located in the main branch of your
-          repository. It serves as a testing ground for new GitHub Actions on
-          development branches before merging them to the main branch. By
-          defining and overloading this workflow on your development branch,
-          you can test new actions without affecting your main branch, ensuring
-          a smooth integration process once the changes are ready to be merged.
-
-          Usage:
-          
-          1. In your development branch, modify the sandbox.yml workflow file
-             to include the new actions you want to test. Make sure to commit
-             the changes to the development branch.
-          2. Navigate to the 'Actions' tab in your repository, select the
-             '~Sandbox' workflow, and choose your development branch from the
-             branch dropdown menu. Click on 'Run workflow' to trigger the
-             workflow on your development branch.
-          3. Once you have tested and verified the new actions in the Sandbox
-             workflow, you can incorporate them into your main workflow(s) and
-             merge the development branch into the main branch. Remember to
-             revert the changes to the sandbox.yml file in the main branch to
-             keep it empty for future testing.
-          EOF
+    env:
+      IMAGE_NAME: ghcr.io/nvidia/jax-toolbox-internal:10352352914-maxtext-amd64
+    uses: ./.github/workflows/_test_unit.yaml
+    with:
+      TEST_NAME: nsys-jax
+      EXECUTE: |
+        # Test cases:
+        # - 1 GPU, profiled from the beginning
+        # - 1 GPU, with targeted collection that's too short
+        # - 1 GPU, with targeted collection that's sufficient
+        # - multi-GPU
+        # in principle all of them with/without analysis recipes,
+        # but probably not worth actually doing that
+        NSYS_JAX="docker run --shm-size=1g --gpus all ${IMAGE_NAME} nsys-jax"
+        ${NSYS_JAX} --nsys-jax-analysis summary test-maxtext.sh |& tee full-execution.log
+        num_failures=$(($? != 0))
+        ${NSYS_JAX} --nsys-jax-analysis summary \
+          --capture-range=cudaProfilerApi \
+          --capture-range-end=stop -- \
+          --sample=none \
+          test-maxtext.sh \
+          --additional-args "profiler=nsys skip_first_n_steps_for_profiler=4 profiler_steps=5" \
+          --steps 10 |& tee partial-execution.log
+        num_failures=$((num_failures + ($? != 0)))
+        ls -R .
+        exit $num_failures
+      STATISTICS_SCRIPT: |
+        # errors=$(cat test-*.log | grep -c 'ERROR:' || true)
+        # failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true)
+        # passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true)
+        # total_tests=$((failed_tests + passed_tests))
+        # echo "TOTAL_TESTS=${total_tests}" >> $GITHUB_OUTPUT
+        # echo "ERRORS=${errors}" >> $GITHUB_OUTPUT
+        # echo "PASSED_TESTS=${passed_tests}" >> $GITHUB_OUTPUT
+        # echo "FAILED_TESTS=${failed_tests}" >> $GITHUB_OUTPUT
+        echo "TOTAL_TESTS=3" >> $GITHUB_OUTPUT
+        echo "ERRORS=1" >> $GITHUB_OUTPUT
+        echo "PASSED_TESTS=1" >> $GITHUB_OUTPUT
+        echo "FAILED_TESTS=1" >> $GITHUB_OUTPUT
+      ARTIFACTS: |
+        full-execution.log
+        partial-execution.log
+    secrets: inherit
