refactor JAX unit test reporting

diff --git a/.github/workflows/_test_jax.yaml b/.github/workflows/_test_jax.yaml
--- a/.github/workflows/_test_jax.yaml
+++ b/.github/workflows/_test_jax.yaml
@@ -78,12 +78,12 @@ jobs:
           ls -lR
           BADGE_LABEL='${{ matrix.GPU_ARCH }} Unit'
 
-          errors=$(grep -c 'ERROR:' test-*.log || true)
-          failed_tests=$(grep -c 'FAILED in' test-*.log || true)
-          passed_tests=$(grep -c 'PASSED in' test-*.log || true)
+          errors=$(cat test-*.log | grep -c 'ERROR:' || true)
+          failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true)
+          passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true)
           total_tests=$((failed_tests + passed_tests))
 
-          if [[ ${errors} -gt 0 ]] || [[ ${total_tests} == 0 ]]; then
+          if [[ ${errors} > 0 ]] || [[ ${total_tests} == 0 ]]; then
             BADGE_MESSAGE='error'
             BADGE_COLOR=red
             SUMMARY='JAX unit test on ${{ matrix.GPU_ARCH }} did not complete due to errors.'
