nightly T5X perf

diff --git a/.github/workflows/_test_t5x.yaml b/.github/workflows/_test_t5x.yaml
--- a/.github/workflows/_test_t5x.yaml
+++ b/.github/workflows/_test_t5x.yaml
@@ -32,16 +32,15 @@ jobs:
           TZ="America/Los_Angeles" DATE=$(date "+%Y-%m-%d")
           echo "DATE=${DATE}" >> $GITHUB_ENV
 
+      - name: Add known SSH host
+        shell: bash -x -e {0}
+        run: |
+          echo "150.230.212.101 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcOJt0Q0qYfShF03/rFPYpq+muMHBIfMlvitzEsSm4onWkG4YU0NBvG5WKcU2dLoMdhCIy+SQYtDeNm9Lj5GIqsLSsVMBSAurIMAzyiJU3DuahiWQGMa3rOVEFzgRtmo58202Ijw61WwVi47OvzJL72Oy2RO8hqVvU0ojcQo1jiQxtj39u1Be7dzIXJHLs7xdpI7V8mGxwQ1dgcjcXSh43br9V24pAebK2abGD8KRZ1H0YDgyaYek0ub5AHAeeznL/FUs0lud1xicABd5qo+w1PyIA+1A+TkRTrbHCBtc2w9w3zaO4p+Yi/ITTjhtnPTAmTD7U+km2mhiR+dLbx15D" >> ~/.ssh/known_hosts
+
       - name: Run SLURM jobs over SSH
-        uses: appleboy/ssh-action@v0.1.9
-        with:
-          host: ${{ secrets.CLUSTER_LOGIN_IP }}
-          fingerprint: ${{ secrets.CLUSTER_LOGIN_FINGERPRINT }}
-          username: ${{ secrets.CLUSTER_LOGIN_USER }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script_stop: true  # stop on first failure
-          command_timeout: 60m
-          script: |
+        shell: bash -x -e {0}
+        run: |
+          ssh ${{ secrets.CLUSTER_LOGIN_USER }}@${{ secrets.CLUSTER_LOGIN_IP }} << EOF
             set -ex
             date
             hostname
@@ -68,8 +67,49 @@ jobs:
                 --gpus ${GPU_LIST} \
                 --epochs 7 \
                 --steps-per-epoch 100
-            EOF)
+            EOF
+            )
             ls ${OUTPUT}
+          EOF
+
+      # - name: Run SLURM jobs over SSH
+      #   uses: appleboy/ssh-action@v0.1.9
+      #   with:
+      #     host: ${{ secrets.CLUSTER_LOGIN_IP }}
+      #     fingerprint: ${{ secrets.CLUSTER_LOGIN_FINGERPRINT }}
+      #     username: ${{ secrets.CLUSTER_LOGIN_USER }}
+      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
+      #     script_stop: true  # stop on first failure
+      #     command_timeout: 60m
+      #     script: |
+      #       set -ex
+      #       date
+      #       hostname
+      #       whoami
+      #       sinfo
+      #       NNODE=1
+      #       NGPU=8
+      #       GPU_LIST=$(seq 0 $(($NNODE - 1)))
+      #       OUTPUT=$(mktemp -d -p /nfs/cluster)
+      #       JOB=$(sbatch << EOF
+      #       #!/bin/bash
+      #       #SBATCH --nodes=${NNODE}
+      #       #SBATCH --gpus-per-node=${NGPU}
+      #       #SBATCH --time=00:30:00
+      #       #SBATCH --exclusive
+      #       srun \
+      #         --container-image=ghcr.io#nvidia/t5x:latest \
+      #         --container-mounts=${OUTPUT}:/output \
+      #         --container-entrypoint \
+      #         test-t5x.sh \
+      #           --output /output/$DATE-${NGPU}G${NNODE}N \
+      #           --dtype bfloat16 \
+      #           --batch-per-gpu 16 \
+      #           --gpus ${GPU_LIST} \
+      #           --epochs 7 \
+      #           --steps-per-epoch 100
+      #       EOF)
+      #       ls ${OUTPUT}
 
       #   run: |
       #     NGPU=8
