test te

diff --git a/.github/workflows/_test_te.yaml b/.github/workflows/_test_te.yaml
--- a/.github/workflows/_test_te.yaml
+++ b/.github/workflows/_test_te.yaml
@@ -115,6 +115,7 @@ jobs:
       CONTAINER_REGISTRY_TOKEN: ${{ secrets.github_token }}
     with:
       NAME: te-${{ matrix.N_GPU }}GPU
+      ARTIFACT_NAME: ${{ inputs.ARTIFACT_NAME }}-${{ matrix.N_GPU }}GPU
       SLURM_LOGIN_HOSTNAME: ${{ vars.HOSTNAME_SLURM_LOGIN }}
       SLURM_SCRATCH_PATH: /nfs/cluster
       NODES: 1
@@ -139,55 +140,66 @@ jobs:
           test_multigpu_encoder.py \
           test_model_parallel_encoder.py
 
-  # sitrep:
-  #   needs: te-multi-gpu
-  #   if: success() || failure()
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Generate sitrep
-  #       shell: bash -x -e {0}
-  #       run: |
-  #         # bring in utility functions
-  #         source .github/workflows/scripts/to_json.sh
+  sitrep:
+    needs: te-multi-gpu
+    if: success() || failure()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out the repository under ${GITHUB_WORKSPACE}
+        uses: actions/checkout@v4
 
-  #         EXIT_STATUSES="output/*-status.json"
-  #         badge_label='TE Multi GPU tests'
-  #         passed_tests=$(jq -r '. | select ((.state == "COMPLETED") and (.exitcode == "0")) | .state' $EXIT_STATUSES | wc -l)
-  #         failed_tests=$(jq -r '. | select ((.state != "COMPLETED") or (.exitcode != "0")) | .state' $EXIT_STATUSES | wc -l)
-  #         total_tests=$(ls $EXIT_STATUSES | wc -l)
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: artifacts/
+          pattern: ${{ inputs.ARTIFACT_NAME }}-*
+          merge-multiple: true
+
+      - name: Generate sitrep
+        shell: bash -x -e {0}
+        run: |
+          ls -lR artifacts/
+      #     # bring in utility functions
+      #     source .github/workflows/scripts/to_json.sh
+
+      #     EXIT_STATUSES="output/*-status.json"
+      #     badge_label='TE Multi GPU tests'
+      #     passed_tests=$(jq -r '. | select ((.state == "COMPLETED") and (.exitcode == "0")) | .state' $EXIT_STATUSES | wc -l)
+      #     failed_tests=$(jq -r '. | select ((.state != "COMPLETED") or (.exitcode != "0")) | .state' $EXIT_STATUSES | wc -l)
+      #     total_tests=$(ls $EXIT_STATUSES | wc -l)
           
-  #         if [[ ${failed_tests} > 0 ]] || [[ ${total_tests} == 0 ]]; then
-  #           badge_message='error'
-  #           badge_color=red
-  #           summary='TE multi GPU tests did not complete due to errors.'
-  #         else
-  #           badge_message="${passed_tests}/${total_tests} passed"
-  #           if [[ ${failed_tests} == 0 ]]; then
-  #             badge_color=brightgreen
-  #           else
-  #             badge_color=yellow
-  #           fi
-  #           summary="TE multi GPU tests : $badge_message"
-  #         fi
+      #     if [[ ${failed_tests} > 0 ]] || [[ ${total_tests} == 0 ]]; then
+      #       badge_message='error'
+      #       badge_color=red
+      #       summary='TE multi GPU tests did not complete due to errors.'
+      #     else
+      #       badge_message="${passed_tests}/${total_tests} passed"
+      #       if [[ ${failed_tests} == 0 ]]; then
+      #         badge_color=brightgreen
+      #       else
+      #         badge_color=yellow
+      #       fi
+      #       summary="TE multi GPU tests : $badge_message"
+      #     fi
 
-  #         to_json \
-  #           summary \
-  #           total_tests passed_tests failed_tests \
-  #           badge_label badge_color badge_message \
-  #         > sitrep.json
+      #     to_json \
+      #       summary \
+      #       total_tests passed_tests failed_tests \
+      #       badge_label badge_color badge_message \
+      #     > sitrep.json
 
-  #         schemaVersion=1 \
-  #         label="${badge_label}" \
-  #         message="${badge_message}" \
-  #         color="${badge_color}" \
-  #         to_json schemaVersion label message color \
-  #         > ${{ env.BADGE_FILENAME_FULL }}
+      #     schemaVersion=1 \
+      #     label="${badge_label}" \
+      #     message="${badge_message}" \
+      #     color="${badge_color}" \
+      #     to_json schemaVersion label message color \
+      #     > ${{ env.BADGE_FILENAME_FULL }}
           
-  #     - name: Upload training logs as artifacts
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: ${{ env.ARTIFACT_NAME_FULL }}
-  #         path: |
-  #           output/
-  #           sitrep.json
-  #           ${{ env.BADGE_FILENAME_FULL }}
+      # - name: Upload training logs as artifacts
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: ${{ env.ARTIFACT_NAME_FULL }}
+      #     path: |
+      #       output/
+      #       sitrep.json
+      #       ${{ env.BADGE_FILENAME_FULL }}
