hacky way to merge jax and pallas workflow

diff --git a/.github/workflows/_test_unit.yaml b/.github/workflows/_test_unit.yaml
--- a/.github/workflows/_test_unit.yaml
+++ b/.github/workflows/_test_unit.yaml
@@ -5,24 +5,22 @@ on:
     inputs:
       IMAGE:
         type: string
-        description: 'Docker image to be tested'
+        description: 'Image to be tested'
         required: true
-      TEST_COMMANDS:
+      TEST_NAME:
         type: string
-        description: 'Test commands to run'
-        required: true
-      POSTPROC_COMMANDS:
-        type: string
-        description: 'Postprocessing commands, e.g. for generating sitreps'
+        description: 'Name of the test, must be jax or pallas'
         required: true
       ARTIFACT_NAME:
         type: string
         description: 'Name of the artifact zip file'
         required: true
-      ARTIFACT_FILES:
+        # default: 'artifact-jax-unit-test'
+      BADGE_FILENAME:
         type: string
-        description: a list/glob pattern of files to upload as artifacts
-        required: true
+        description: 'Name of the endpoint JSON file for shields.io badge'
+        required: false
+        # default: 'badge-jax-unit-test'
 
 jobs:
   runner:
@@ -33,7 +31,103 @@ jobs:
       TIME: "01:00:00"
     secrets: inherit
 
-  run-test:
+  jax-unit-test:
+    if: ${{ inputs.TEST_NAME == 'jax' }}
+    strategy:
+      fail-fast: false
+      matrix:
+        GPU_ARCH: [V100, A100]
+    # ensures A100 job lands on dedicated runner for this particular job
+    runs-on: [self-hosted, "${{ matrix.GPU_ARCH == 'A100' && format('{0}:{1}', matrix.GPU_ARCH, github.run_id) || matrix.GPU_ARCH }}"]
+    env:
+      BADGE_FILENAME_FULL: ${{ inputs.BADGE_FILENAME }}-${{ matrix.GPU_ARCH }}.json
+    steps:
+      - name: Print environment variables
+        run: env
+
+      - name: Print GPU information
+        run: nvidia-smi  
+
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Pull JAX image
+        shell: bash -x -e {0}
+        run: |
+          docker pull ${{ inputs.IMAGE }}
+
+      - name: Backend-independent tests
+        shell: bash -x -e {0}
+        # todo: distinguish between test failures and errors
+        continue-on-error: true
+        run: |
+          docker run --gpus all ${{ inputs.IMAGE }} test-jax.sh -b backend-independent | tee test-backend-independent.log
+
+      - name: GPU-specific tests
+        shell: bash -x -e {0}
+        continue-on-error: true
+        run: |
+          docker run --gpus all ${{ inputs.IMAGE }} test-jax.sh -b gpu | tee test-gpu.log
+
+      - name: Generate sitrep
+        shell: bash -x -e {0}
+        run: |
+          # bring in utility functions
+          source .github/workflows/scripts/to_json.sh
+
+          badge_label='JAX ${{ matrix.GPU_ARCH }} Unit'
+
+          errors=$(cat test-*.log | grep -c 'ERROR:' || true)
+          failed_tests=$(cat test-*.log | grep -c 'FAILED in' || true)
+          passed_tests=$(cat test-*.log | grep -c 'PASSED in' || true)
+          total_tests=$((failed_tests + passed_tests))
+
+          if [[ ${errors} > 0 ]] || [[ ${total_tests} == 0 ]]; then
+            badge_message='error'
+            badge_color=red
+            summary='JAX unit test on ${{ matrix.GPU_ARCH }} did not complete due to errors.'
+          else
+            badge_message="${passed_tests}/${total_tests} passed"
+            if [[ ${failed_tests} == 0 ]]; then
+              badge_color=brightgreen
+            else
+              badge_color=yellow
+            fi
+            summary="JAX unit test on ${{ matrix.GPU_ARCH }}: $badge_message"
+          fi
+
+          to_json \
+            summary \
+            errors total_tests passed_tests failed_tests \
+            badge_label badge_color badge_message \
+          > sitrep.json
+
+          schemaVersion=1 \
+          label="${badge_label}" \
+          message="${badge_message}" \
+          color="${badge_color}" \
+          to_json schemaVersion label message color \
+          > ${{ env.BADGE_FILENAME_FULL }}
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ inputs.ARTIFACT_NAME }}-${{ matrix.GPU_ARCH }}
+          path: |
+            test-backend-independent.log
+            test-gpu.log
+            sitrep.json
+            ${{ env.BADGE_FILENAME_FULL }}
+
+  pallas-unit-test:
+    if: ${{ inputs.TEST_NAME == 'pallas' }}
     strategy:
       fail-fast: false
       matrix:
@@ -59,22 +153,64 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Pull image
+      - name: Pull Pallas image
         shell: bash -x -e {0}
         run: |
           docker pull ${{ inputs.IMAGE }}
 
-      - name: Run tests
-        shell: bash -exu -o pipefail {0}
+      - name: Run Pallas tests
+        shell: bash -x -e {0}
         continue-on-error: true
-        run: ${{ inputs.TEST_COMMANDS }}
+        run: |
+          docker run --shm-size=1g --gpus all --volume $PWD:/output ${{ inputs.IMAGE }} python /opt/jax/tests/pallas/pallas_test.py --xml_output_file /output/pallas_test.xml | tee test-pallas.log
 
-      - name: Run postprocessing
-        shell: bash -exu -o pipefail {0}
-        run: ${{ inputs.POSTPROC_COMMANDS }}
+      - name: Generate sitrep
+        shell: bash -x -e {0}
+        run: |
+          # bring in utility functions
+          source .github/workflows/scripts/to_json.sh
+
+          curl -L -o yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$(dpkg --print-architecture) && chmod 777 yq
+
+          badge_label='${{ matrix.GPU_ARCH }} Pallas'
+
+          total_tests=$(./yq '.testsuites."+@tests"' pallas_test.xml)
+          errors=$(./yq '.testsuites."+@errors"' pallas_test.xml)
+          failed_tests=$(./yq '.testsuites."+@failures"' pallas_test.xml)
+          passed_tests=$((total_tests - errors - failed_tests))
+
+          if [[ ${errors} > 0 ]] || [[ ${total_tests} == 0 ]]; then
+            badge_message='error'
+            badge_color=red
+            summary='Pallas test on ${{ matrix.GPU_ARCH }} did not complete due to errors.'
+          else
+            badge_message="${passed_tests}/${total_tests} passed"
+            if [[ ${failed_tests} == 0 ]]; then
+              badge_color=brightgreen
+            else
+              badge_color=yellow
+            fi
+            summary="Pallas unit test on ${{ matrix.GPU_ARCH }}: $badge_message"
+          fi
+
+          to_json \
+            summary \
+            errors total_tests passed_tests failed_tests \
+            badge_label badge_color badge_message \
+          > sitrep.json
+
+          schemaVersion=1 \
+          label="${badge_label}" \
+          message="${badge_message}" \
+          color="${badge_color}" \
+          to_json schemaVersion label message color \
+          > ${{ env.BADGE_FILENAME_FULL }}
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v3
         with:
           name: ${{ inputs.ARTIFACT_NAME }}-${{ matrix.GPU_ARCH }}
-          path: ${{ inputs.ARTIFACT_FILES }}
+          path: |
+            test-pallas.log
+            sitrep.json
+            ${{ env.BADGE_FILENAME_FULL }}
