PR feedback part 1

diff --git a/.github/workflows/_test_t5x.yaml b/.github/workflows/_test_t5x.yaml
--- a/.github/workflows/_test_t5x.yaml
+++ b/.github/workflows/_test_t5x.yaml
@@ -22,7 +22,7 @@ on:
           type: string
           description: 'Name of the endpoint JSON file for shields.io badge'
           required: false
-          default: 'badge-t5x-mgmn-test'
+          default: 'badge-t5x-mgmn-test.json'
       ARTIFACT_NAME:
         type: string
         description: 'Name of the artifact zip file'
@@ -47,20 +47,20 @@ jobs:
       - name: Print environment variables
         run: env
 
-      - name: Setup SSH agent
-        uses: webfactory/ssh-agent@v0.8.0
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      # - name: Setup SSH agent
+      #   uses: webfactory/ssh-agent@v0.8.0
+      #   with:
+      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Setup SSH known hosts
-        id: ssh-known-hosts
-        run: |
-          mkdir -p ~/.ssh
-          cat >> ~/.ssh/known_hosts << EOF
-          ${{ vars.SSH_KNOWN_HOSTS }}
-          EOF
-          chmod 600 ~/.ssh/known_hosts
-          echo "FILE=$(realpath ~/.ssh/known_hosts)" >> $GITHUB_OUTPUT
+      # - name: Setup SSH known hosts
+      #   id: ssh-known-hosts
+      #   run: |
+      #     mkdir -p ~/.ssh
+      #     cat >> ~/.ssh/known_hosts << EOF
+      #     ${{ vars.SSH_KNOWN_HOSTS }}
+      #     EOF
+      #     chmod 600 ~/.ssh/known_hosts
+      #     echo "FILE=$(realpath ~/.ssh/known_hosts)" >> $GITHUB_OUTPUT
 
       - name: Labels and metadata
         id: meta
@@ -76,75 +76,77 @@ jobs:
             echo "$var=${!var}" >> $GITHUB_OUTPUT
           done
 
-      - name: Submit SLURM jobs over SSH
-        id: submit
-        shell: bash -O expand_aliases -x -e {0}
-        run: |
-          alias sshx='ssh -o "ServerAliveInterval 7" ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}'
-          sshx "date && hostname && sinfo"
-          sshx mkdir -p ${{ steps.meta.outputs.MODEL_PATH }}
-          JOB=$(sshx sbatch --parsable << EOF
-          #!/bin/bash
-          #SBATCH --job-name=${{ steps.meta.outputs.JOB_NAME }}
-          #SBATCH --exclusive
-          #SBATCH --nodes=1
-          #SBATCH --tasks=1
-          #SBATCH --gpus-per-node=${{ matrix.N_GPU }}
-          #SBATCH --time=00:30:00
-          #SBATCH --output=${{ steps.meta.outputs.LOG_FILE }}
-          #SBATCH --export="ENROOT_PASSWORD=${{ secrets.GITHUB_TOKEN }}"
-          time srun \
-            --container-image=${{ steps.meta.outputs.IMAGE }} \
-            --container-mounts=${{ steps.meta.outputs.MODEL_PATH }}:/output \
-            --container-entrypoint \
-            test-t5x.sh \
-              --output /output/${{ steps.meta.outputs.TEST_CASE_NAME }} \
-              --dtype bfloat16 \
-              --batch-size ${{ steps.meta.outputs.BATCH_SIZE }} \
-              --epochs 7 \
-              --steps-per-epoch 100 \
-              ${{ inputs.EXTRA_GIN_ARGS != '' && format('--additional-args "{0}"', inputs.EXTRA_GIN_ARGS) || '' }}
-          EOF
-          )
+      # - name: Submit SLURM jobs over SSH
+      #   id: submit
+      #   shell: bash -O expand_aliases -x -e {0}
+      #   run: |
+      #     alias sshx='ssh -o "ServerAliveInterval 7" ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}'
+      #     sshx "date && hostname && sinfo"
+      #     sshx mkdir -p ${{ steps.meta.outputs.MODEL_PATH }}
+      #     JOB=$(sshx sbatch --parsable << EOF
+      #     #!/bin/bash
+      #     #SBATCH --job-name=${{ steps.meta.outputs.JOB_NAME }}
+      #     #SBATCH --exclusive
+      #     #SBATCH --nodes=1
+      #     #SBATCH --tasks=1
+      #     #SBATCH --gpus-per-node=${{ matrix.N_GPU }}
+      #     #SBATCH --time=00:30:00
+      #     #SBATCH --output=${{ steps.meta.outputs.LOG_FILE }}
+      #     #SBATCH --export="ENROOT_PASSWORD=${{ secrets.GITHUB_TOKEN }}"
+      #     time srun \
+      #       --container-image=${{ steps.meta.outputs.IMAGE }} \
+      #       --container-mounts=${{ steps.meta.outputs.MODEL_PATH }}:/output \
+      #       --container-entrypoint \
+      #       test-t5x.sh \
+      #         --output /output/${{ steps.meta.outputs.TEST_CASE_NAME }} \
+      #         --dtype bfloat16 \
+      #         --batch-size ${{ steps.meta.outputs.BATCH_SIZE }} \
+      #         --epochs 7 \
+      #         --steps-per-epoch 100 \
+      #         ${{ inputs.EXTRA_GIN_ARGS != '' && format('--additional-args "{0}"', inputs.EXTRA_GIN_ARGS) || '' }}
+      #     EOF
+      #     )
 
-          set +x
-          while sshx squeue -j $JOB | grep -q $JOB; do
-            echo "SLURM Job $JOB is still running."
-            sleep 15
-          done
-          echo "SLRUM Job $JOB finished."
+      #     set +x
+      #     while sshx squeue -j $JOB | grep -q $JOB; do
+      #       echo "SLURM Job $JOB is still running."
+      #       sleep 15
+      #     done
+      #     echo "SLRUM Job $JOB finished."
 
-          # Gather job info
-          SLURM_STATE=$(sshx sacct -j $JOB --format=State --parsable2 --noheader |& head -n 1)
-          SLURM_EXITCODE=$(sshx sacct -j $JOB --format=exitcode --parsable2 --noheader | sort -r -u | head -1 | cut -f 1 -d":" | sed 's/ //g')
-          echo "SLURM Job state is ${SLURM_STATE}"
-          echo "SLURM Job exit code is ${SLURM_EXITCODE}"
-          echo "SLURM_STATE=${SLURM_STATE}" >> "$GITHUB_OUTPUT"
-          echo "SLURM_EXITCODE=${SLURM_EXITCODE}" >> "$GITHUB_OUTPUT"
+      #     # Gather job info
+      #     SLURM_STATE=$(sshx sacct -j $JOB --format=State --parsable2 --noheader |& head -n 1)
+      #     SLURM_EXITCODE=$(sshx sacct -j $JOB --format=exitcode --parsable2 --noheader | sort -r -u | head -1 | cut -f 1 -d":" | sed 's/ //g')
+      #     echo "SLURM Job state is ${SLURM_STATE}"
+      #     echo "SLURM Job exit code is ${SLURM_EXITCODE}"
+      #     echo "SLURM_STATE=${SLURM_STATE}" >> "$GITHUB_OUTPUT"
+      #     echo "SLURM_EXITCODE=${SLURM_EXITCODE}" >> "$GITHUB_OUTPUT"
 
-          set -x
+      #     set -x
 
-      - name: Retrieve training logs and upload to TensorBoard server
-        shell: bash -x -e {0}
-        run: |
-          mkdir output/
-          rsync -rtz --progress \
-            ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.LOG_FILE }} \
-            output/${{ steps.meta.outputs.TEST_CASE_NAME }}.log || true
-          rsync -rtz --progress \
-            ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.MODEL_PATH }}/* \
-            output/ || true
-          rsync -rtz --progress \
-            output/ \
-            ${{ secrets.TENSORBOARD_UPLOAD_USER }}@${{ vars.HOSTNAME_TENSORBOARD }}:/tensorboard-logs/${GITHUB_RUN_ID}/ || true
+      # - name: Retrieve training logs and upload to TensorBoard server
+      #   shell: bash -x -e {0}
+      #   run: |
+      #     mkdir output/
+      #     rsync -rtz --progress \
+      #       ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.LOG_FILE }} \
+      #       output/${{ steps.meta.outputs.TEST_CASE_NAME }}.log || true
+      #     rsync -rtz --progress \
+      #       ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.MODEL_PATH }}/* \
+      #       output/ || true
+      #     rsync -rtz --progress \
+      #       output/ \
+      #       ${{ secrets.TENSORBOARD_UPLOAD_USER }}@${{ vars.HOSTNAME_TENSORBOARD }}:/tensorboard-logs/${GITHUB_RUN_ID}/ || true
 
       - name: Write SLURM job status to file
         shell: bash -x -e {0}
         run: |
+          mkdir output/
+          touch "output/${{ steps.meta.outputs.TEST_CASE_NAME }}-status.json"
           python << EOF
           import json
           with open("output/${{ steps.meta.outputs.TEST_CASE_NAME }}-status.json", "w") as f:
-              dump = {'state': "${{ steps.submit.outputs.SLURM_STATE }}", 'exitcode': "${{ steps.submit.outputs.SLURM_EXITCODE }}"}
+              dump = {'state': "COMPLETED", 'exitcode': "0"}
               json.dump(dump, f)
           EOF
 
@@ -167,20 +169,20 @@ jobs:
       - name: Print environment variables
         run: env
 
-      - name: Setup SSH agent
-        uses: webfactory/ssh-agent@v0.8.0
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      # - name: Setup SSH agent
+      #   uses: webfactory/ssh-agent@v0.8.0
+      #   with:
+      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Setup SSH known hosts
-        id: ssh-known-hosts
-        run: |
-          mkdir -p ~/.ssh
-          cat >> ~/.ssh/known_hosts << EOF
-          ${{ vars.SSH_KNOWN_HOSTS }}
-          EOF
-          chmod 600 ~/.ssh/known_hosts
-          echo "FILE=$(realpath ~/.ssh/known_hosts)" >> $GITHUB_OUTPUT
+      # - name: Setup SSH known hosts
+      #   id: ssh-known-hosts
+      #   run: |
+      #     mkdir -p ~/.ssh
+      #     cat >> ~/.ssh/known_hosts << EOF
+      #     ${{ vars.SSH_KNOWN_HOSTS }}
+      #     EOF
+      #     chmod 600 ~/.ssh/known_hosts
+      #     echo "FILE=$(realpath ~/.ssh/known_hosts)" >> $GITHUB_OUTPUT
 
       - name: Labels and metadata
         id: meta
@@ -197,78 +199,80 @@ jobs:
             echo "$var=${!var}" >> $GITHUB_OUTPUT
           done
 
-      - name: Submit SLURM jobs over SSH
-        id: submit
-        shell: bash -O expand_aliases -x -e {0}
-        run: |
-          alias sshx='ssh -o "ServerAliveInterval 7" ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}'
-          sshx "date && hostname && sinfo"
-          sshx mkdir -p ${{ steps.meta.outputs.MODEL_PATH }}
-          JOB=$(sshx sbatch --parsable << EOF
-          #!/bin/bash
-          #SBATCH --job-name=${{ steps.meta.outputs.JOB_NAME }}
-          #SBATCH --exclusive
-          #SBATCH --nodes=${{ matrix.N_NODE }}
-          #SBATCH --gpus-per-node=${{ matrix.N_GPU }}
-          #SBATCH --tasks=${{ steps.meta.outputs.TOTAL_TASKS }}
-          #SBATCH --tasks-per-node=${{ matrix.N_GPU }}
-          #SBATCH --time=00:30:00
-          #SBATCH --output=${{ steps.meta.outputs.LOG_FILE }}
-          #SBATCH --export="ENROOT_PASSWORD=${{ secrets.GITHUB_TOKEN }}"
-          time srun \
-            --container-image=${{ steps.meta.outputs.IMAGE }} \
-            --container-mounts=${{ steps.meta.outputs.MODEL_PATH }}:/output \
-            --container-entrypoint \
-            test-t5x.sh \
-              --output /output/${{ steps.meta.outputs.TEST_CASE_NAME }} \
-              --dtype bfloat16 \
-              --batch-size ${{ steps.meta.outputs.BATCH_SIZE }} \
-              --epochs 7 \
-              --steps-per-epoch 100 \
-              --multiprocess \
-              ${{ inputs.EXTRA_GIN_ARGS != '' && format('--additional-args "{0}"', inputs.EXTRA_GIN_ARGS) || '' }}
-          EOF
-          )
+      # - name: Submit SLURM jobs over SSH
+      #   id: submit
+      #   shell: bash -O expand_aliases -x -e {0}
+      #   run: |
+      #     alias sshx='ssh -o "ServerAliveInterval 7" ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}'
+      #     sshx "date && hostname && sinfo"
+      #     sshx mkdir -p ${{ steps.meta.outputs.MODEL_PATH }}
+      #     JOB=$(sshx sbatch --parsable << EOF
+      #     #!/bin/bash
+      #     #SBATCH --job-name=${{ steps.meta.outputs.JOB_NAME }}
+      #     #SBATCH --exclusive
+      #     #SBATCH --nodes=${{ matrix.N_NODE }}
+      #     #SBATCH --gpus-per-node=${{ matrix.N_GPU }}
+      #     #SBATCH --tasks=${{ steps.meta.outputs.TOTAL_TASKS }}
+      #     #SBATCH --tasks-per-node=${{ matrix.N_GPU }}
+      #     #SBATCH --time=00:30:00
+      #     #SBATCH --output=${{ steps.meta.outputs.LOG_FILE }}
+      #     #SBATCH --export="ENROOT_PASSWORD=${{ secrets.GITHUB_TOKEN }}"
+      #     time srun \
+      #       --container-image=${{ steps.meta.outputs.IMAGE }} \
+      #       --container-mounts=${{ steps.meta.outputs.MODEL_PATH }}:/output \
+      #       --container-entrypoint \
+      #       test-t5x.sh \
+      #         --output /output/${{ steps.meta.outputs.TEST_CASE_NAME }} \
+      #         --dtype bfloat16 \
+      #         --batch-size ${{ steps.meta.outputs.BATCH_SIZE }} \
+      #         --epochs 7 \
+      #         --steps-per-epoch 100 \
+      #         --multiprocess \
+      #         ${{ inputs.EXTRA_GIN_ARGS != '' && format('--additional-args "{0}"', inputs.EXTRA_GIN_ARGS) || '' }}
+      #     EOF
+      #     )
 
-          set +x
-          while sshx squeue -j $JOB | grep -q $JOB; do
-            echo "SLURM Job $JOB is still running."
-            sleep 15
-          done
-          echo "SLRUM Job $JOB finished."
+      #     set +x
+      #     while sshx squeue -j $JOB | grep -q $JOB; do
+      #       echo "SLURM Job $JOB is still running."
+      #       sleep 15
+      #     done
+      #     echo "SLRUM Job $JOB finished."
 
-          # Gather job info
-          SLURM_STATE=$(sshx sacct -j $JOB --format=State --parsable2 --noheader |& head -n 1)
-          SLURM_EXITCODE=$(sshx sacct -j $JOB --format=exitcode --parsable2 --noheader | sort -r -u | head -1 | cut -f 1 -d":" | sed 's/ //g')
-          echo "SLURM Job state is ${SLURM_STATE}"
-          echo "SLURM Job exit code is ${SLURM_EXITCODE}"
-          echo "SLURM_STATE=${SLURM_STATE}" >> "$GITHUB_OUTPUT"
-          echo "SLURM_EXITCODE=${SLURM_EXITCODE}" >> "$GITHUB_OUTPUT"
+      #     # Gather job info
+      #     SLURM_STATE=$(sshx sacct -j $JOB --format=State --parsable2 --noheader |& head -n 1)
+      #     SLURM_EXITCODE=$(sshx sacct -j $JOB --format=exitcode --parsable2 --noheader | sort -r -u | head -1 | cut -f 1 -d":" | sed 's/ //g')
+      #     echo "SLURM Job state is ${SLURM_STATE}"
+      #     echo "SLURM Job exit code is ${SLURM_EXITCODE}"
+      #     echo "SLURM_STATE=${SLURM_STATE}" >> "$GITHUB_OUTPUT"
+      #     echo "SLURM_EXITCODE=${SLURM_EXITCODE}" >> "$GITHUB_OUTPUT"
 
-          set -x
+      #     set -x
 
-      - name: Retrieve training logs and upload to TensorBoard server
-        shell: bash -x -e {0}
-        run: |
+      # - name: Retrieve training logs and upload to TensorBoard server
+      #   shell: bash -x -e {0}
+      #   run: |
 
-          mkdir output/
-          rsync -rtz --progress \
-            ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.LOG_FILE }} \
-            output/${{ steps.meta.outputs.TEST_CASE_NAME }}.log || true
-          rsync -rtz --progress \
-            ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.MODEL_PATH }}/* \
-            output/ || true
-          rsync -rtz --progress \
-            output/ \
-            ${{ secrets.TENSORBOARD_UPLOAD_USER }}@${{ vars.HOSTNAME_TENSORBOARD }}:/tensorboard-logs/${GITHUB_RUN_ID}/ || true
+      #     mkdir output/
+      #     rsync -rtz --progress \
+      #       ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.LOG_FILE }} \
+      #       output/${{ steps.meta.outputs.TEST_CASE_NAME }}.log || true
+      #     rsync -rtz --progress \
+      #       ${{ secrets.CLUSTER_LOGIN_USER }}@${{ vars.HOSTNAME_SLURM_LOGIN }}:${{ steps.meta.outputs.MODEL_PATH }}/* \
+      #       output/ || true
+      #     rsync -rtz --progress \
+      #       output/ \
+      #       ${{ secrets.TENSORBOARD_UPLOAD_USER }}@${{ vars.HOSTNAME_TENSORBOARD }}:/tensorboard-logs/${GITHUB_RUN_ID}/ || true
 
       - name: Write SLURM job status to file
         shell: bash -x -e {0}
         run: |
+          mkdir output/
+          touch "output/${{ steps.meta.outputs.TEST_CASE_NAME }}-status.json"
           python << EOF
           import json
           with open("output/${{ steps.meta.outputs.TEST_CASE_NAME }}-status.json", "w") as f:
-              dump = {'state': "${{ steps.submit.outputs.SLURM_STATE }}", 'exitcode': "${{ steps.submit.outputs.SLURM_EXITCODE }}"}
+              dump = {'state': "FAILED", 'exitcode': "1"}
               json.dump(dump, f)
           EOF
 
@@ -298,14 +302,6 @@ jobs:
             mv $i/$SUBDIR* .
             python3 .github/workflows/baselines/summarize_metrics.py $SUBDIR --perf_summary_name "timing/steps_per_second" # create result json in baseline format
           done
-
-          echo '## T5X MGMN Test Metrics' >> $GITHUB_STEP_SUMMARY
-          for i in *_metrics.json; do
-            echo $i | cut -d'.' -f1
-            echo '```json'
-            jq . $i
-            echo '```'
-          done | tee -a $GITHUB_STEP_SUMMARY
 
           RESULTS_DIR=$PWD pytest --report-log=report.jsonl .github/workflows/baselines/test_t5x_mgmn_metrics.py || true
 
