reintroduce _ci_tmp.yml to test w/ pass/fail test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -136,7 +136,8 @@ jobs:
 
   amd64:
     needs: [metadata, bump-manifest]
-    uses: ./.github/workflows/_ci.yaml
+    #uses: ./.github/workflows/_ci.yaml
+    uses: ./.github/workflows/_ci_tmp.yaml
     with:
       ARCHITECTURE: amd64
       BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
@@ -145,7 +146,8 @@ jobs:
 
   arm64:
     needs: [metadata, bump-manifest]
-    uses: ./.github/workflows/_ci.yaml
+    #uses: ./.github/workflows/_ci.yaml
+    uses: ./.github/workflows/_ci_tmp.yaml
     with:
       ARCHITECTURE: arm64
       BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
@@ -238,115 +240,115 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  make-publish-configs:
-    runs-on: ubuntu-22.04
-    if:  ${{ !cancelled() }}
-    env:
-      MEALKIT_IMAGE_REPO: ${{ needs.metadata.outputs.PUBLISH == 'true' && 'jax-mealkit' || 'mock-jax-mealkit' }}
-      FINAL_IMAGE_REPO: ${{ needs.metadata.outputs.PUBLISH == 'true' && 'jax' || 'mock-jax' }}
-    needs:
-      - metadata
-      - amd64
-      - arm64
-    outputs:
-      PUBLISH_CONFIGS: ${{ steps.generate-configs.outputs.PUBLISH_CONFIGS }}
-    steps:
-      - id: generate-configs
-        shell: bash -eu -o pipefail {0}
-        run: |
-          declare -a FLAVORS=(
-            base
-            jax
-            pallas
-            maxtext
-            levanter
-            upstream-t5x
-            upstream-pax
-            t5x
-            pax
-          )
-          declare -a STAGES=(
-            mealkit
-            final
-          )
+  #make-publish-configs:
+  #  runs-on: ubuntu-22.04
+  #  if:  ${{ !cancelled() }}
+  #  env:
+  #    MEALKIT_IMAGE_REPO: ${{ needs.metadata.outputs.PUBLISH == 'true' && 'jax-mealkit' || 'mock-jax-mealkit' }}
+  #    FINAL_IMAGE_REPO: ${{ needs.metadata.outputs.PUBLISH == 'true' && 'jax' || 'mock-jax' }}
+  #  needs:
+  #    - metadata
+  #    - amd64
+  #    - arm64
+  #  outputs:
+  #    PUBLISH_CONFIGS: ${{ steps.generate-configs.outputs.PUBLISH_CONFIGS }}
+  #  steps:
+  #    - id: generate-configs
+  #      shell: bash -eu -o pipefail {0}
+  #      run: |
+  #        declare -a FLAVORS=(
+  #          base
+  #          jax
+  #          pallas
+  #          maxtext
+  #          levanter
+  #          upstream-t5x
+  #          upstream-pax
+  #          t5x
+  #          pax
+  #        )
+  #        declare -a STAGES=(
+  #          mealkit
+  #          final
+  #        )
 
-          ## create JSON specs for a 1D matrix of container publication jobs
+  #        ## create JSON specs for a 1D matrix of container publication jobs
 
-          ALL_TAGS=$(
-            echo '${{ needs.amd64.outputs.DOCKER_TAGS }}' \
-                 '${{ needs.arm64.outputs.DOCKER_TAGS }}' |\
-            jq -s 'add'
-          )
-          PUBLISH_CONFIGS='[]'
+  #        ALL_TAGS=$(
+  #          echo '${{ needs.amd64.outputs.DOCKER_TAGS }}' \
+  #               '${{ needs.arm64.outputs.DOCKER_TAGS }}' |\
+  #          jq -s 'add'
+  #        )
+  #        PUBLISH_CONFIGS='[]'
 
-          for stage in "${STAGES[@]}"; do
-            for flavor in "${FLAVORS[@]}";do
+  #        for stage in "${STAGES[@]}"; do
+  #          for flavor in "${FLAVORS[@]}";do
 
-              # collect images for different platforms, e.g. amd64 and arm64
-              matching_tags=$(
-                echo "$ALL_TAGS" |\
-                jq -c ".[] | select(.stage == \"${stage}\" and .flavor == \"${flavor}\" and .tag != \"\")"
-              )
+  #            # collect images for different platforms, e.g. amd64 and arm64
+  #            matching_tags=$(
+  #              echo "$ALL_TAGS" |\
+  #              jq -c ".[] | select(.stage == \"${stage}\" and .flavor == \"${flavor}\" and .tag != \"\")"
+  #            )
 
-              # source_image is a list of all platform-specific tags
-              source_image=$(echo "${matching_tags}" | jq -c "[.tag]" | jq -s 'add')
-              # if the build job failed without producing any images, skip this flavor
-              n_source_images=$(echo "$source_image" | jq 'length')
-              if [[ $n_source_images -gt 0 ]]; then
-                echo "PUBLISH image $flavor with $n_source_images $stage containers"
+  #            # source_image is a list of all platform-specific tags
+  #            source_image=$(echo "${matching_tags}" | jq -c "[.tag]" | jq -s 'add')
+  #            # if the build job failed without producing any images, skip this flavor
+  #            n_source_images=$(echo "$source_image" | jq 'length')
+  #            if [[ $n_source_images -gt 0 ]]; then
+  #              echo "PUBLISH image $flavor with $n_source_images $stage containers"
 
-                # tag priority is the highest priority of all platform-specific tags
-                priority=$(echo "${matching_tags}" | jq -r ".priority" | jq -s 'max')
+  #              # tag priority is the highest priority of all platform-specific tags
+  #              priority=$(echo "${matching_tags}" | jq -r ".priority" | jq -s 'max')
 
-                # put all final images in the `ghcr.io/nvidia/jax` namespace
-                # and mealkit images in `ghcr.io/nvidia/jax-toolbox-mealkit` namespace
-                case ${stage} in
-                  mealkit)
-                    target_image=${MEALKIT_IMAGE_REPO}
-                    ;;
-                  final)
-                    target_image=${FINAL_IMAGE_REPO}
-                    ;;
-                esac
+  #              # put all final images in the `ghcr.io/nvidia/jax` namespace
+  #              # and mealkit images in `ghcr.io/nvidia/jax-toolbox-mealkit` namespace
+  #              case ${stage} in
+  #                mealkit)
+  #                  target_image=${MEALKIT_IMAGE_REPO}
+  #                  ;;
+  #                final)
+  #                  target_image=${FINAL_IMAGE_REPO}
+  #                  ;;
+  #              esac
 
-                PUBLISH_CONFIGS=$(
-                  echo ${PUBLISH_CONFIGS} | jq -c ". + [{
-                    \"flavor\": \"${flavor}\",
-                    \"target_image\": \"${target_image}\",
-                    \"priority\": \"${priority}\",
-                    \"source_image\": ${source_image}
-                  }]"
-                )
-              else
-                echo "SKIPPED image $flavor with 0 $stage containers"
-              fi
-            done
-          done
+  #              PUBLISH_CONFIGS=$(
+  #                echo ${PUBLISH_CONFIGS} | jq -c ". + [{
+  #                  \"flavor\": \"${flavor}\",
+  #                  \"target_image\": \"${target_image}\",
+  #                  \"priority\": \"${priority}\",
+  #                  \"source_image\": ${source_image}
+  #                }]"
+  #              )
+  #            else
+  #              echo "SKIPPED image $flavor with 0 $stage containers"
+  #            fi
+  #          done
+  #        done
 
-          PUBLISH_CONFIGS=$(echo "$PUBLISH_CONFIGS" | jq -c '{"config": .}')
-          echo ${PUBLISH_CONFIGS} | jq
-          echo "PUBLISH_CONFIGS=${PUBLISH_CONFIGS}" >> $GITHUB_OUTPUT
+  #        PUBLISH_CONFIGS=$(echo "$PUBLISH_CONFIGS" | jq -c '{"config": .}')
+  #        echo ${PUBLISH_CONFIGS} | jq
+  #        echo "PUBLISH_CONFIGS=${PUBLISH_CONFIGS}" >> $GITHUB_OUTPUT
 
-  publish-containers:
-    needs:
-      - metadata
-      - make-publish-configs
-    if:  ${{ !cancelled() && needs.make-publish-configs.outputs.PUBLISH_CONFIGS.config != '{"config":[]}' }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.make-publish-configs.outputs.PUBLISH_CONFIGS) }}
-    uses: ./.github/workflows/_publish_container.yaml
-    with:
-      SOURCE_IMAGE: ${{ join(matrix.config.source_image, ' ') }}
-      TARGET_IMAGE: ${{ matrix.config.target_image }}
-      TARGET_TAGS: |
-        type=raw,value=${{ matrix.config.flavor }},priority=${{ matrix.config.priority }}
-        type=raw,value=${{ matrix.config.flavor }}-${{ needs.metadata.outputs.BUILD_DATE }},priority=${{ matrix.config.priority }}
+  #publish-containers:
+  #  needs:
+  #    - metadata
+  #    - make-publish-configs
+  #  if:  ${{ !cancelled() && needs.make-publish-configs.outputs.PUBLISH_CONFIGS.config != '{"config":[]}' }}
+  #  strategy:
+  #    fail-fast: false
+  #    matrix: ${{ fromJson(needs.make-publish-configs.outputs.PUBLISH_CONFIGS) }}
+  #  uses: ./.github/workflows/_publish_container.yaml
+  #  with:
+  #    SOURCE_IMAGE: ${{ join(matrix.config.source_image, ' ') }}
+  #    TARGET_IMAGE: ${{ matrix.config.target_image }}
+  #    TARGET_TAGS: |
+  #      type=raw,value=${{ matrix.config.flavor }},priority=${{ matrix.config.priority }}
+  #      type=raw,value=${{ matrix.config.flavor }}-${{ needs.metadata.outputs.BUILD_DATE }},priority=${{ matrix.config.priority }}
 
-  finalize:
-    needs: [metadata, amd64, arm64]
-    if: "!cancelled()"
-    uses: ./.github/workflows/_finalize.yaml
-    with:
-      PUBLISH_BADGE: ${{ needs.metadata.outputs.PUBLISH == 'true' }}
-    secrets: inherit
+  #finalize:
+  #  needs: [metadata, amd64, arm64]
+  #  if: "!cancelled()"
+  #  uses: ./.github/workflows/_finalize.yaml
+  #  with:
+  #    PUBLISH_BADGE: ${{ needs.metadata.outputs.PUBLISH == 'true' }}
+  #  secrets: inherit
