Add cutlass

diff --git a/.github/workflows/eks-jobset-test.yml b/.github/workflows/eks-jobset-test.yml
--- a/.github/workflows/eks-jobset-test.yml
+++ b/.github/workflows/eks-jobset-test.yml
@@ -11,61 +11,104 @@ permissions:
   packages: write       # to upload containers
 
 jobs:
-  test-maxtext-single-node:
+  test-cutlass:
+    runs-on: eks
     strategy:
       fail-fast: false
       matrix:
         include:
-          - test: single-node
-            nodes: 1
+          - nodes: 1
             gpus: 8
-            pipeline-parallel: 1
-            data-parallel: 1
-            fsdp: 2
-            tensor-parallel: 4
-            envs: |-
-              NCCL_IB_DISABLE=1
-              NCCL_P2P_DISABLE=1
-              NCCL_NET_PLUGIN=none
-              NCCL_NET=Socket
-          - test: multi-node
-            nodes: 2
-            gpus: 8
-            pipeline-parallel: 1
-            data-parallel: 4
-            fsdp: 2
-            tensor-parallel: 2
-            envs: |-
-              OFI_NCCL_PROTOCOL=SENDRECV
-    runs-on: eks
+            
     steps:
       - uses: actions/checkout@v4
       - name: Run eks-jobset action
         uses: ./.github/actions/eks-jobset
         with:
-          NAME: maxtext-${{ matrix.test }}
+          NAME: jax-cutlass
           NUM_NODES: ${{ matrix.nodes }}
           NUM_GPUS: ${{ matrix.gpus }}
-          IMAGE: ghcr.io/nvidia/jax-toolbox-internal:24448213493-maxtext-amd64
-          ENVS: |
-            ${{ matrix.envs }}
+          IMAGE: ghcr.io/nvidia/jax-toolbox-internal:25104098695-jax-amd64
           COMMAND: |
-            test-maxtext.sh \
-              --output /opt/output \
-              --batch-per-gpu 2 \
-              --steps 10 \
-              --model-name=llama2-7b \
-              --attn-type cudnn_flash_te \
-              --remat-policy=minimal_with_context \
-              --pipeline-parallel ${{ matrix.pipeline-parallel }} \
-              --data-parallel ${{ matrix.data-parallel }} \
-              --fsdp ${{ matrix.fsdp }} \
-              --tensor-parallel ${{ matrix.tensor-parallel }} \
-              --nodes ${{ matrix.nodes }} \
-              -a 'scan_layers=false 
-                  max_target_length=1024 
-                  use_iota_embed=true
-                  logits_dot_in_fp32=false 
-                  max_segments_per_seq=32'
+            pip install pytest-reportlog pytest-xdist flatbuffers;
+            CUTEDSL_VERSION=\$(python -c 'import cutlass; print(cutlass.__version__);');
+            git clone -b v\${CUTEDSL_VERSION} --single-branch --depth 1 https://github.com/NVIDIA/cutlass.git /cutlass
+            NGPUS=\$(nvidia-smi --list-gpus | wc -l);
+            nvidia-cuda-mps-control -d;
+            
+            for f in /cutlass/examples/python/CuTeDSL/jax/*.py; do
+              echo \"[Executing] \${f}\";
+              log_output=\$(python \${f} 2>&1);
+              exit_code=\${?};
+              outcome=\$( [ \${exit_code} -eq 0 ] && echo \"passed\" || echo \"failed\" );
+              echo \"=== \${f} ===\" | tee -a /opt/output/pytest_stdout.log;
+              echo \"\${log_output}\" | tee -a /opt/output/pytest_stdout.log;
+              python3 -c \"import json,sys; print(json.dumps({'outcome': sys.argv[1], 'nodeid': sys.argv[2], 'longrepr': sys.argv[3]}))\" \
+                 \"\${outcome}\" \"\${f}" \"\${log_output}\" >> /opt/output/pytest-report.jsonl;
+            done
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NVCR_TOKEN: ${{ secrets.NVCR_TOKEN }}
+          STATISTICS: true
+          STATISTICS_SCRIPT: |
+            NUM_PASSED=\$(cat \${JOBSET_NAME}/pytest-report.jsonl | jq --slurp | jq '.[] | select(.outcome == \"passed\") | .outcome' | wc -l || true);
+            NUM_FAILED=\$(cat \${JOBSET_NAME}/pytest-report.jsonl | jq --slurp | jq '.[] | select(.outcome == \"failed\") | .outcome' | wc -l || true);
+            NUM_TESTS=\$(( NUM_PASSED + NUM_FAILED ));
+
+#  test-maxtext-single-node:
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - test: single-node
+#            nodes: 1
+#            gpus: 8
+#            pipeline-parallel: 1
+#            data-parallel: 1
+#            fsdp: 2
+#            tensor-parallel: 4
+#            envs: |-
+#              NCCL_IB_DISABLE=1
+#              NCCL_P2P_DISABLE=1
+#              NCCL_NET_PLUGIN=none
+#              NCCL_NET=Socket
+#          - test: multi-node
+#            nodes: 2
+#            gpus: 8
+#            pipeline-parallel: 1
+#            data-parallel: 4
+#            fsdp: 2
+#            tensor-parallel: 2
+#            envs: |-
+#              OFI_NCCL_PROTOCOL=SENDRECV
+#    runs-on: eks
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Run eks-jobset action
+#        uses: ./.github/actions/eks-jobset
+#        with:
+#          NAME: maxtext-${{ matrix.test }}
+#          NUM_NODES: ${{ matrix.nodes }}
+#          NUM_GPUS: ${{ matrix.gpus }}
+#          IMAGE: ghcr.io/nvidia/jax-toolbox-internal:24448213493-maxtext-amd64
+#          ENVS: |
+#            ${{ matrix.envs }}
+#          COMMAND: |
+#            test-maxtext.sh \
+#              --output /opt/output \
+#              --batch-per-gpu 2 \
+#              --steps 10 \
+#              --model-name=llama2-7b \
+#              --attn-type cudnn_flash_te \
+#              --remat-policy=minimal_with_context \
+#              --pipeline-parallel ${{ matrix.pipeline-parallel }} \
+#              --data-parallel ${{ matrix.data-parallel }} \
+#              --fsdp ${{ matrix.fsdp }} \
+#              --tensor-parallel ${{ matrix.tensor-parallel }} \
+#              --nodes ${{ matrix.nodes }} \
+#              -a 'scan_layers=false 
+#                  max_target_length=1024 
+#                  use_iota_embed=true
+#                  logits_dot_in_fp32=false 
+#                  max_segments_per_seq=32'
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          NVCR_TOKEN: ${{ secrets.NVCR_TOKEN }}
